# first install/upgrade numpy
# pip install numpy --upgrade 

BASICS

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3]) # 1D
a

array([1, 2, 3])

In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype='int64') #2D
print(b) 

[[9 8 7]
 [6 5 4]]


In [5]:
a.ndim #tells dimension

1

In [6]:
b.ndim 

2

In [7]:
a.shape  #gives shape

(3,)

In [8]:
b.dtype

dtype('int64')

In [9]:
a.itemsize

4

In [10]:
a.size 

3

In [11]:
a.nbytes #a.itemsize * a.size

12

# ACCESSING/CHANGINE specific elements,row, columns, etc

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a[1,5]

13

slicing/selection

In [15]:
a[0,:] # get a specific row

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
a[:,2] # get a specific column

array([ 3, 10])

In [17]:
a[0,1:6:2] # start,end, difference

array([2, 4, 6])

In [18]:
a[0,1:-1:2] # both are same // negative index

array([2, 4, 6])

In [19]:
a[1,5]=20 # to change value
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [20]:
a[:,1:2]=[58]
print(a)
a[:,2]=[85,35]
a

[[ 1 58  3  4  5  6  7]
 [ 8 58 10 11 12 20 14]]


array([[ 1, 58, 85,  4,  5,  6,  7],
       [ 8, 58, 35, 11, 12, 20, 14]])

In [21]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D example
print (c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# get a specific element
c[:,1,1]=[88,77]
c

array([[[ 1,  2],
        [ 3, 88]],

       [[ 5,  6],
        [ 7, 77]]])

# Initializing Different types of arrays

### remember matrix/vector is
#### ROW X COLUMN

In [23]:
d=np.zeros((1,2)) # all zeros
d.ndim

2

In [24]:
e=np.ones((4,3,3),dtype='int32') # all ones
e

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [25]:
f=np.full((3,3),99,dtype='float32') # takes a defined value
f

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [26]:
f=np.full(a.shape,4)
f

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
f=np.full_like(b,4)
f

array([[4, 4, 4],
       [4, 4, 4]], dtype=int64)

In [28]:
g=np.random.rand(2,2,3) # create a random matrix of any dim
g

array([[[0.51435371, 0.37968167, 0.82901631],
        [0.74014811, 0.79812745, 0.53774443]],

       [[0.4852085 , 0.98359206, 0.27501011],
        [0.76780325, 0.55588925, 0.93670617]]])

In [29]:
g=np.random.random_sample(c.shape,) # CREATE MATRIX BASED ON OTHER SHAPE
g

array([[[0.39669853, 0.00667451],
        [0.67974461, 0.09681865]],

       [[0.65924195, 0.02752247],
        [0.25609983, 0.43619943]]])

In [30]:
# int random numbers with specific limits
g=np.random.randint(3,8,size=(3,3))
g

array([[6, 7, 4],
       [5, 3, 4],
       [4, 4, 6]])

In [31]:
g=np.random.randint(-8,8,size=(5,2))
g

array([[-7, -3],
       [ 5,  6],
       [ 2, -4],
       [-7,  5],
       [-7,  6]])

In [32]:
h=np.identity(5)
h

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
h=np.identity(8,dtype='int32')
h


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [34]:
# repeating an array

arr=np.array([[1,2,3]])
i=np.repeat(arr,3,axis=0)
i

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [35]:
output=np.ones((5,5),dtype='int32')
print(output)
z=np.zeros((3,3),dtype='int32')
print(z)
z[1,1]=9
print(z)
output[1:4,1:4]=z
output

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [36]:
j=i.copy()
j

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Mathematics

In [37]:
k=np.array([1,2,3])
k

array([1, 2, 3])

In [38]:
k+2

array([3, 4, 5])

In [39]:
k-2

array([-1,  0,  1])

In [40]:
k/2

array([0.5, 1. , 1.5])

In [41]:
k%3

array([1, 2, 0], dtype=int32)

In [42]:
l=np.random.rand(k.size,1)
l

array([[0.07441584],
       [0.7428817 ],
       [0.95459626]])

In [43]:
k+l # see carefully above and this cell

array([[1.07441584, 2.07441584, 3.07441584],
       [1.7428817 , 2.7428817 , 3.7428817 ],
       [1.95459626, 2.95459626, 3.95459626]])

In [44]:
k**2

array([1, 4, 9], dtype=int32)

In [45]:
print(k)
k1=np.cos(k)
k1

[1 2 3]


array([ 0.54030231, -0.41614684, -0.9899925 ])

In [46]:
k2=np.sin(k)
k2

array([0.84147098, 0.90929743, 0.14112001])

In [47]:
k3=np.tan(k)
k3

array([ 1.55740772, -2.18503986, -0.14254654])

# Linear Algebra

In [58]:
l=np.ones((2,3),dtype='int32')
print(l)
m=np.full((3,2),2)
print(m)

np.matmul(l,m)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [59]:
# find determinant
n=np.identity(5)
n1=np.linalg.det(n)
n1

1.0

# Statistics

In [64]:
stat1=np.array([[1,2,3],[4,5,6]])
stat1

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.min(stat1)
np.min(stat1,axis=1) # minimum of matrix

array([1, 4])

In [74]:
np.max(stat1)  # maximum of matrix

6

In [75]:
np.sum(stat1) # sum of matrix

21

# Reorganizing Arrays

In [80]:
past=np.array([[1,2,3,4],[5,6,7,8]])
print(past)
print(past.shape)

present=past.reshape((8,1)) # reshape matrix
print(present)

present=past.reshape((2,2,2))
print(present)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
# vertical stacking

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2]),"VERTICAL")
print(np.hstack((v1,v2)),"HORIZONTAL")

[[1 2 3 4]
 [5 6 7 8]] VERTICAL
[1 2 3 4 5 6 7 8] HORIZONTAL


# LOAD DATA FILE

In [95]:
filedata=np.genfromtxt('data.txt',delimiter=',',dtype='int32')
print(filedata)
print('\n',filedata.shape,'shape')

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

 (3, 18) shape


In [96]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [97]:
filedata<30

array([[ True,  True,  True,  True, False, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [110]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [111]:
test=f.reshape((6,1))
print(test)
test[[1,2,5]]

[[4]
 [4]
 [4]
 [4]
 [4]
 [4]]


array([[4],
       [4],
       [4]], dtype=int64)

In [113]:
np.all(filedata >50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [117]:
(~((filedata >50) & (filedata <90))) # opposite / negation operation over checking values

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [122]:
test =list(range(1,31))
print(test)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [133]:
t1=np.ones((6,5),dtype='int32')
t1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])